### ISSUE TITLE
Non mirrored CHR banks causes out of bounds memory access

### ISSUE THREAD

**Issue by KasumiArai** [kgabis/agnes#2]
I created a ROM that can crash the emulator or allow it to access out of bounds memory.

The ROM essentially writes a value from 0 to 255 to the MMC3 CHR banks registers, then increments this value every frame.

If the ROM has just one bank, the expected behavior is for that one bank to be mirrored.

I fixed it in the tool I included agnes in with modulus at the mapper level, but this breaks CHR RAM and doesn't properly respect powers of two for mirroring. 
```c
	int modValue = mapper->agnes->gamepack.chr_rom_banks_count*8;
    switch (mapper->chr_mode) {
        case 0: { // R0_1, R0_2, R1_1, R1_2, R2, R3, R4, R5
            mapper->chr_bank_offsets[0] = ((mapper->regs[0]%modValue) & 0xfe) * 1024;
			//similar modulus for all other lines
```
A real fix would probably be to allocate memory to the next power of two at load (for weird CHR bank values like 3 rather than 4), then AND instead of %

I've attached the ROM (It is homebrew, not commercial):
[anim.zip](https://github.com/kgabis/agnes/files/3088540/anim.zip)

**Comment by kgabis** [comment]
Does https://github.com/kgabis/agnes/commit/b84d7fad7fd396ec4e0a08eda8c665ff854edeaa fix this issue?
Just to be clear, I wouldn't trust agnes with roms from unknown sources because it's possible that there are more out of bounds memory access bugs (it's still in beta).
Also, out of curiosity, what tool are you using agnes in?

**Comment by KasumiArai** [comment]
Yes, that fixes it. No ROMs from unknown sources. It only loads tool output unless the user modifies the given ROM (which will still have data hacked onto it by the tool) or write locks the output filename. A user could craft data that once transformed causes issues, but I'd fear more for an earlier step in the process.

It is an NES data management tool called I-CHR: https://kasumi.itch.io/ichr
But the public version is very far behind. Here's a GIF showing agnes use in my local version: 
![ilZhcIA](https://user-images.githubusercontent.com/8582123/56284216-db9e3f00-60e1-11e9-9a8f-00a04054dd7d.gif)
