### ISSUE TITLE
Why header only?

### ISSUE THREAD

**Issue by fpemud** [kgabis/agnes#3]
The concept of NES emulation library is great.
I think release it as a dynamically linked library is good enough, why restrict to header-only?

**Comment by kgabis** [comment]
See https://github.com/nothings/stb#why-single-file-headers
Besides these advantages I find it really convenient to have all dependencies in your source tree, without having to worry about users having a different version of your library. Also, being able to debug and modify your dependencies is really helpful and saves a lot of time.
